# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - post-beetmover-dummy

transforms:
    - gecko_taskgraph.transforms.release_update_product_channel_version:transforms
    - gecko_taskgraph.transforms.release_deps:transforms
    - gecko_taskgraph.transforms.release:run_on_releases
    - gecko_taskgraph.transforms.task:transforms

job-defaults:
    description: Update product channel version in Ship-It
    attributes:
        shippable: true
    worker-type: shipit
    worker:
        implementation: shipit-update-product-channel-version
    scopes:
        by-release-level:
            production:
                - project:releng:ship-it:server:production
                - project:releng:ship-it:action:update-product-channel-version
            staging:
                - project:releng:ship-it:server:staging
                - project:releng:ship-it:action:update-product-channel-version
    shipping-phase: ship
    treeherder:
        symbol: Rel(up-chl-ver)
        kind: other
        tier: 1

jobs:
    firefox:
        run-on-releases: ["nightly"]
        run-on-projects: ["mozilla-central"]
        shipping-product: firefox
        treeherder:
            platform: firefox-release/opt
