/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef DOM_BASE_JSEXECUTIONUTILS_H_
#define DOM_BASE_JSEXECUTIONUTILS_H_

#include "js/TypeDecls.h"               // JSScript, MutableHandle
#include "js/Value.h"                   // JS::UndefinedHandleValue
#include "js/experimental/JSStencil.h"  // JS::Stencil
#include "js/CompileOptions.h"          // JS::CompileOptions
#include "js/RootingAPI.h"              // JS::Handle
#include "mozilla/ErrorResult.h"        // ErrorResult
#include "nsStringFwd.h"                // nsAString

namespace mozilla::dom {

nsresult EvaluationExceptionToNSResult(ErrorResult& aRv);

// Compile a script contained in a string.
void Compile(JSContext* aCx, JS::CompileOptions& aCompileOptions,
             const nsAString& aScript, RefPtr<JS::Stencil>& aStencil,
             ErrorResult& aRv);

// Instantiate (on main-thread) a JS::Stencil generated by off-thread or
// main-thread parsing or decoding.
void InstantiateStencil(JSContext* aCx, JS::CompileOptions& aCompileOptions,
                        RefPtr<JS::Stencil>&& aStencil,
                        JS::MutableHandle<JSScript*> aScript,
                        bool& incrementalEncodingAlreadyStarted,
                        JS::Handle<JS::Value> aDebuggerPrivateValue,
                        JS::Handle<JSScript*> aDebuggerIntroductionScript,
                        ErrorResult& aRv, bool aEncodeBytecode = false,
                        JS::InstantiationStorage* aStorage = nullptr);

}  // namespace mozilla::dom

#endif /* DOM_BASE_JSEXECUTIONUTILS_H_ */
