FROM rust:1.82 as build

RUN git clone https://github.com/mozilla/rust-code-analysis && \
    cd rust-code-analysis && \
    git checkout efe9894 && \
    cargo build -p rust-code-analysis-cli --release -v

FROM python:3.9.18-slim

RUN apt-get update && apt-get install -y wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=build /rust-code-analysis/target/release/rust-code-analysis-cli /usr/local/bin/

RUN pip install --no-cache-dir poetry==1.7

RUN useradd -ms /bin/bash scripts
USER scripts

WORKDIR /home/scripts/qm-try-analysis

COPY ./ .
RUN poetry install --only main

ENTRYPOINT /bin/bash -c "poetry shell && exec /bin/bash -i"
