[package]
name = "webdriver"
version = "0.40.2"
authors = ["Mozilla"]
description = "Library implementing the wire protocol for the W3C WebDriver specification."
keywords = ["webdriver", "browser", "automation", "protocol", "w3c"]
documentation = "https://docs.rs/webdriver"
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/webdriver"
readme = "README.md"
license = "MPL-2.0"

[dependencies]
base64 = "0.10"
cookie = { version = "0.12", default-features = false }
http = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
time = "0.1"
tokio = "0.1"
unicode-segmentation = "1.2"
url = "2.0"
warp = { version = "0.1", default-features = false }
