/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(6937FB48-0912-11E5-85D3-611D1E5D46B0)]
interface nsICloudStorageGeckoInterface : nsISupports
{
  void setFileMeta(in AUTF8String cloudname,
                   in AUTF8String path,
                   in boolean isDir,
                   in unsigned long long size,
                   in unsigned long long mtime,
                   in unsigned long long ctime);

  void setFileList(in AUTF8String cloudname,
                   in AUTF8String path,
                   in AUTF8String childpath,
                   in boolean isdir,
                   in unsigned long long size,
                   in unsigned long long mtime,
                   in unsigned long long ctime);

  void setData(in AUTF8String cloudname,
               [array, size_is(length)] in octet buffer,
               in unsigned long length );

  void finishRequest(in AUTF8String cloudname);
 
};

