[package]
name = "u2fhid"
version = "0.2.2"
authors = ["Kyle Machulis <kyle@nonpolynomial.com>", "J.C. Jones <jc@mozilla.com>", "Tim Taubert <ttaubert@mozilla.com>"]

[target.'cfg(target_os = "linux")'.dependencies]
libudev = "^0.2"

[target.'cfg(target_os = "freebsd")'.dependencies]
devd-rs = "0.2.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.6.0"
core-foundation = "0.6.0"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3"
features = [
    "handleapi",
    "hidclass",
    "hidpi",
    "hidusage",
    "setupapi",
]

[dependencies]
rand = "0.3"
log = "0.4"
libc = "^0.2"
boxfnonce = "0.0.3"
runloop = "0.1.0"
bitflags = "1.0"

[dev-dependencies]
sha2 = "^0.7"
base64 = "^0.4"
env_logger = "0.5"
