[package]
name = "geckoservo"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"

[lib]
name = "geckoservo"
path = "lib.rs"

[features]
bindgen = ["style/use_bindgen"]
gecko_debug = ["style/gecko_debug", "nsstring/gecko_debug"]

[dependencies]
atomic_refcell = "0.1"
cssparser = "0.25"
cstr = "0.1.2"
libc = "0.2"
log = {version = "0.4", features = ["release_max_level_info"]}
malloc_size_of = {path = "../../components/malloc_size_of"}
nsstring = {path = "../../support/gecko/nsstring"}
num-traits = "0.2"
parking_lot = "0.6"
selectors = {path = "../../components/selectors"}
servo_arc = {path = "../../components/servo_arc"}
smallvec = "0.6"
style = {path = "../../components/style", features = ["gecko"]}
style_traits = {path = "../../components/style_traits"}
