/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(9a28937E-997f-4962-9422-f8a2103214bc)]
interface nsIQuotaArtificialFailure : nsISupports
{
  cenum Category : 32 {
    CATEGORY_NONE = 0,
    CATEGORY_INITIALIZE_ORIGIN = 1 << 0,
    CATEGORY_OPEN_CLIENT_DIRECTORY = 1 << 1,
    CATEGORY_CREATE_DIRECTORY_METADATA2 = 1 << 2,
  };
};
