/* -*- Mode: C++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 8 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

// This skeleton allows control/replay JS to be set up with contents
// determined at runtime.
[scriptable, uuid(840753da-74ff-43ce-89e9-c1f75816b2f5)]
interface rrIModule : nsISupports {
  jsval Initialize(in ACString moduleText);
};
