[package]
name = "webrender_api"
version = "0.57.2"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/servo/webrender"
description = "Public API for WebRender"

[features]
nightly = ["euclid/unstable", "serde/unstable"]
ipc = ["ipc-channel"]
serialize = []
deserialize = []

[dependencies]
app_units = "0.7"
bincode = "1.0"
bitflags = "1.0"
byteorder = "1.2.1"
ipc-channel = {version = "0.11.0", optional = true}
euclid = { version = "0.19.3", features = ["serde"] }
serde = { version = "=1.0.80", features = ["rc"] }
serde_derive = { version = "=1.0.80", features = ["deserialize_in_place"] }
serde_bytes = "0.10"
time = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6"
core-graphics = "0.17.1"

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.6.2"
