image: Visual Studio 2017
before_test:
  - ps: iex (Get-Content -Raw ci-scripts\set-screenresolution.ps1)
  - ps: Set-ScreenResolution 1920 1080

environment:
  PATH: 'C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Rust\bin'
  RUST_BACKTRACE: 1
  TARGET: x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.36.0-${env:TARGET}.msi"
  - msiexec /passive /i "rust-1.36.0-%TARGET%.msi" ADDLOCAL=Rustc,Cargo,Std INSTALLDIR=C:\Rust
  - rustc -V
  - cargo -V

build: false

test_script:
  - cmd.exe /c ci-scripts\windows-tests.cmd
