before_test:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1920 1080

environment:
  PATH: 'C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Rust\bin'
  RUST_BACKTRACE: 1
  TARGET: x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.30.0-${env:TARGET}.msi"
  - msiexec /passive /i "rust-1.30.0-%TARGET%.msi" ADDLOCAL=Rustc,Cargo,Std INSTALLDIR=C:\Rust
  - rustc -V
  - cargo -V

build: false

test_script:
  - cd webrender_api
  - cargo test --verbose
  - cd ../webrender
  - cargo test --verbose
  - cargo check --verbose --no-default-features --features pathfinder
  - cd ../wrench
  - cargo test --verbose
  - cargo run --release -- --angle reftest
  - cd ../examples
  - cargo check --verbose
  - cd ../direct-composition
  - cargo check --verbose
