[configs]
skip-check-length = false
skip-check-licenses = false
check-alphabetical-order = false

[ignore]
# Ignored packages with duplicated versions
packages = [
    # transition to bitflags 2 is underway.
    "bitflags",
    "cfg-if",
    "core-foundation",
    "core-foundation-sys",
    "core-graphics",
    # requires a new version of font-loader, see https://github.com/matprec/rust-font-loader/pull/36
    "core-text",
    # requires updating winit to v0.28 and glutin to v0.30 (to get rid of cocoa v0.24)
    # AND also requires bumping the core-graphics dependency of winit (not present in v0.28)
    "foreign-types",
    "foreign-types-shared",
    # Internal dependencies of glsl-lang (only used in wrench) require different versions.
    "hashbrown",
    # glsl requires 5.1, and xcursor (required by winit) requires 7.1.
    # when a version of glsl depending on 7.1 is published we can update.
    "nom",
    # glsl-lang requires 0.12.1, and glutin requires 0.11.2
    "parking_lot",
    "parking_lot_core",
    "rand",
    "rand_core",
    # rinja (dependency of uniffi) requires 2.1, rowan requires 1.1
    "rustc-hash",
    # transition to syn 2 is underway.
    "syn",
    # Requires an update to clap v4
    "textwrap",
    # Can be fixed by removing time dependency - see bug 1765324
    "wasi",
    # Pulled in by mozangle dev-dep on windows
    "libloading",
    "windows_i686_gnu",
    "windows_x86_64_msvc",
    "windows_x86_64_gnullvm",
    "windows_x86_64_gnu",
    "regex-syntax",
    "windows-targets",
    "windows-sys",
    "windows_aarch64_msvc",
    "windows_i686_msvc",
    "windows_aarch64_gnullvm",
]

# Files that are ignored for all tidy and lint checks.
files = [
    "./wrench/src/egl.rs",  # Copied from glutin
]

# Many directories are currently ignored while we tidy things up
# gradually.
directories = [
   # Generated and upstream code combined with our own. Could use cleanup
  "./target",
  "./webrender/src",
]
