/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * This interface exposes layout of the installation directories
 */
[scriptable, uuid(6b5e9bf7-3a2f-4b05-9bd9-55499450ff81)]
interface nsIInstallationDirLayout : nsISupports {
  /**
   * Does this installation use versioned install directories?
   */
  readonly attribute boolean isInstallationLayoutVersioned;
};
