/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIVirtualFileSystemRequestValue;

[scriptable, uuid(c6cbc0d3-879d-43fc-ba8f-043bb5882535)]
interface nsIVirtualFileSystemResponseHandler : nsISupports
{
  void onSuccess(in unsigned long aRequestId,
                 in nsIVirtualFileSystemRequestValue aValue);
  void onError(in unsigned long aRequestId,
               in unsigned long aError);
};
