[package]
name = "binast"
version = "0.1.1"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[dependencies]
binjs_meta = "^0.4.3"
clap = "^2"
env_logger = "^0.5.6"
itertools = "^0.7.6"
log = "0.4"
yaml-rust = "^0.4"
webidl = "^0.8"
