$inherits:
  from: 'tasks/build.yml'
  variables:
    build_name: 'android'
    build_type: 'opt'
task:
  metadata:
      name: '[TC] Android armv7 API 11+'
      description: 'Android armv7 API 11+'

  workerType: b2g-desktop-opt

  routes:
    - 'index.buildbot.branches.{{project}}.android-api-11'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.android-api-11'

  scopes:
    - 'docker-worker:cache:build-android-api-11-workspace'
    - 'docker-worker:cache:tooltool-cache'

  payload:
    image: '{{#docker_image}}desktop-build{{/docker_image}}'
    cache:
      build-android-api-11-workspace: '/home/worker/workspace'
      tooltool-cache: '/home/worker/tooltool-cache'

    env:
      # inputs to mozharness
      MOZHARNESS_SCRIPT: 'mozharness/scripts/fx_desktop_build.py'
      # TODO: make these additional configuration files go away
      MOZHARNESS_CONFIG: >
          builds/releng_base_android_64_builds.py
          disable_signing.py
          platform_supports_post_upload_to_latest.py
      MH_CUSTOM_BUILD_VARIANT_CFG: api-11
      MH_BRANCH: {{project}}
      MH_BUILD_POOL: taskcluster

      # image paths
      TOOLTOOL_CACHE: '/home/worker/tooltool-cache'

      # authentication
      RELENGAPI_TOKEN: 'TODO' # 1164612: encrypt this secret

    maxRunTime: 36000

    command: ["/bin/bash", "bin/build.sh"]

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      machine:
        # see https://github.com/mozilla/treeherder/blob/master/ui/js/values.js
        platform: android-4-0-armv7-api11
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.linux-x86_64.tar.bz2'
      tests: 'public/build/target.tests.zip'
