$inherits:
  from: 'tasks/build.yml'
task:
  metadata:
    name: "[TC] B2G Desktop ( {{build_type}} )"
    description: B2G Desktop {{build_type}}

  workerType: b2gbuild-desktop
  payload:
    env:
      MOZCONFIG: 'b2g/config/mozconfigs/linux64_gecko/nightly'
      MOZTT_GIT_URL: '{{moztt_git_url}}'
      MOZTT_REVISION: '{{moztt_revision}}'

    command:
      - /bin/bash
      - -c
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/builder &&
        buildbot_step 'Build' ./build-b2g-desktop.sh $HOME/workspace

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      groupSymbol: "?"
      groupName: Submitted by taskcluster
      machine:
        platform: b2g-linux64

    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.linux-x86_64.tar.bz2'
      test_packages: 'public/build/test_packages.json'
