$inherits:
  from: 'tasks/phone_build.yml'
task:
  workerType: dolphin
  metadata:
    description: |
      Dolphin phones + b2g environment used in full stack testing.
  payload:
    env:
      REPO_TRACE: 1
      VARIANT: user
      DEBUG: 0

    # Dolphin could take more than one hours to build!
    maxRunTime: 7200

    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-dolphin.sh $HOME/workspace

  extra:
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'private/build/b2g-android-arm.tar.gz'
      tests: 'private/build/gaia.zip'
      symbols: 'private/build/b2g-crashreporter-symbols.zip'
      sources: 'private/build/sources.xml'
