$inherits:
  from: 'tasks/builds/b2g_dolphin_base.yml'
task:
  scopes:
    - 'docker-worker:cache:build-dolphin-eng'
  metadata:
    name: '[TC] B2G Dolphin Eng'

  extra:
    treeherder:
      symbol: Be
      groupSymbol: Dolphin
      groupName: Dolphin Device Image
      machine:
        platform: b2g-device-image

  payload:
    cache:
      build-dolphin-eng: /home/worker/workspace
    env:
      TARGET: 'dolphin'
      VARIANT: eng
