$inherits:
  from: 'tasks/builds/b2g_dolphin_base.yml'
task:
  scopes:
    - 'docker-worker:cache:build-dolphin-512-opt'
  metadata:
    name: '[TC] B2G Dolphin 512 Opt'

  extra:
    treeherder:
      groupSymbol: Dolphin-512
      groupName: Dolphin 512 Device Image
      machine:
        platform: b2g-device-image

  payload:
    cache:
      build-dolphin-512-opt: /home/worker/workspace
    env:
      TARGET: 'dolphin-512'
