$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
  variables:
    build_name: 'nexus-4-eng'
    build_type: 'opt'
task:
  scopes:
    - 'docker-worker:cache:build-nexus-4-eng'
  metadata:
    name: B2G Nexus 4 Eng
  payload:
    cache:
      build-nexus-4-eng: /home/worker/object-folder
    env:
      TARGET: 'nexus-4'
      DEBUG: 0
  extra:
    locations:
      img: 'private/build/nexus-4.zip'
