$inherits:
  from: 'tasks/builds/b2g_desktop_base.yml'
  variables:
    build_name: 'b2g-desktop'
    build_type: 'opt'
task:
  scopes:
    - 'docker-worker:cache:workspace-b2g-desktop-objects-opt'
  routes:
    - 'index.buildbot.branches.{{project}}.linux64_gecko'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.linux64_gecko'

  workerType: b2g-desktop-opt
  payload:
    cache:
      workspace-b2g-desktop-objects-opt: '/home/worker/workspace'

    env:
      MOZCONFIG: 'b2g/config/mozconfigs/linux64_gecko/nightly'
