$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
  variables:
    build_name: 'helix'
    build_type: 'opt'
task:
  scopes:
    - 'docker-worker:cache:build-helix-user'
  metadata:
    name: B2G Helix User
  payload:
    cache:
      build-hamachi-user: /home/worker/object-folder
    env:
      TARGET: 'helix'
      DEBUG: 0
  extra:
    locations:
      img: 'private/build/helix.zip'
