$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_name: 'emulator-jb'
    build_type: 'debug'
task:
  workerType: emulator-jb-debug
  scopes:
    - 'docker-worker:cache:workspace-emulator-jb-debug'
  metadata:
    name: '[TC] B2G Emulator JB: (Debug)'

  extra:
    # Disable "TC" prefix...
    treeherder:
      groupSymbol: "?"
      collection:
        debug: true
      machine:
        platform: b2g-emu-jb

  payload:
    cache:
      workspace-emulator-jb-debug: /home/worker/workspace
    env:
      TARGET: 'emulator-jb'
      B2G_DEBUG: 1
