$inherits:
  from: 'tasks/builds/b2g_desktop_base.yml'
  variables:
    build_name: 'b2g-desktop'
    build_type: 'debug'

task:
  scopes:
      - 'docker-worker:cache:workspace-b2g-desktop-objects-debug'
  workerType: b2g-desktop-debug
  extra:
    treeherder:
      collection:
        debug: true

  payload:
    cache:
      workspace-b2g-desktop-objects-debug: '/home/worker/workspace'
    env:
      MOZCONFIG: 'b2g/config/mozconfigs/linux64_gecko/debug'
