$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_name: 'emulator-l'
    build_type: 'opt'
task:
  workerType: emulator-l
  scopes:
    - 'docker-worker:cache:workspace-emulator-l-opt'
  metadata:
    name: '[TC] B2G L Emulator (Opt)'

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      # Disable "TC" prefix...
      groupSymbol: "?"
      machine:
        platform: b2g-emu-l

  payload:
    cache:
      workspace-emulator-l-opt: /home/worker/workspace
    env:
      TARGET: 'emulator-l'
