---
metadata:
  name: "Beetmover for checksums artifacts"
  description: "Uploads checksum files to s3 buckets"
  owner: "release@mozilla.com"
s3_bucket_paths:
  - pub/mobile/nightly
default_locales:  # if given an empty locale, use these locales
  - en-US
tasktype_map:  # Map task reference to task type.
  checksums-signing: signing
platform_names:
  path_platform:
    by-platform:
      android-x86-nightly: 'android-x86'
      android-x86_64-nightly: 'android-x86_64'
      android-api-16-nightly: 'android-api-16'
      android-aarch64-nightly: 'android-aarch64'
  filename_platform:
    by-platform:
      android-x86-nightly: 'android-i386'
      android-x86_64-nightly: 'android-x86_64'
      android-api-16-nightly: 'android-arm'
      android-aarch64-nightly: 'android-aarch64'

# A default entry, which the mappings below extend and override.
# Final 'destinations' will be the product of:
# s3_bucket_paths + destinations + locale_prefix + pretty_name
default: &default
  from:
    - checksums-signing
  all_locales: true
  description: "TODO"
  locale_prefix:
    by-locale:
      default: ''
      en-US: '${locale}'
  source_path_modifier: ''
  destinations:  # locale_prefix is appended
    by-locale:
      multi:
        - latest-${branch}-${path_platform}
        - ${year}/${month}/${upload_date}-${branch}-${path_platform}
      en-US:
        - latest-${branch}-${path_platform}
        - ${year}/${month}/${upload_date}-${branch}-${path_platform}
      default:
        - latest-${branch}-${path_platform}-l10n
        - ${year}/${month}/${upload_date}-${branch}-${path_platform}-l10n

# Configuration for individual files. Extends 'default', above.
mapping:
  target.checksums:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.checksums
    checksums_path: fennec-${version}.${locale}.${filename_platform}.checksums
  target.checksums.asc:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.checksums.asc
    checksums_path: fennec-${version}.${locale}.${filename_platform}.checksums.asc
