---
metadata:
  description: Fennec nightly artifacts
  name: Beetmover declarative artifacts manifest
  owner: release@mozilla.com
s3_bucket_paths:
  - pub/mobile/nightly
default_locales:  # if given an empty locale, use these locales
  - en-US
  - multi
tasktype_map:  # Map task reference to task type.
  build: build
  build-signing: signing
  nightly-l10n-signing: signing
platform_names:
  path_platform:
    by-platform:
      android-x86-nightly: 'android-x86'
      android-x86_64-nightly: 'android-x86_64'
      android-api-16-nightly: 'android-api-16'
      android-aarch64-nightly: 'android-aarch64'
  filename_platform:
    by-platform:
      android-x86-nightly: 'android-i386'
      android-x86_64-nightly: 'android-x86_64'
      android-api-16-nightly: 'android-arm'
      android-aarch64-nightly: 'android-aarch64'

# A default entry, which the mappings below extend and override.
# Final 'destinations' will be the product of:
# s3_bucket_paths + destinations + locale_prefix + pretty_name
default: &default
  from:
    - build
  all_locales: false
  description: "TODO"
  locale_prefix:
    by-locale:
      default: ''
      en-US: '${locale}'
  source_path_modifier:  # Anything between artifact prefix and filename
    by-locale:
      default: '${locale}'
      multi: ''
  destinations:  # locale_prefix is appended
    by-locale:
      multi:
        - latest-${branch}-${path_platform}
        - ${year}/${month}/${upload_date}-${branch}-${path_platform}
      en-US:
        - latest-${branch}-${path_platform}
        - ${year}/${month}/${upload_date}-${branch}-${path_platform}
      default:
        - latest-${branch}-${path_platform}-l10n
        - ${year}/${month}/${upload_date}-${branch}-${path_platform}-l10n

# Configuration for individual files. Extends 'default', above.
mapping:
  buildhub.json:
    <<: *default
    all_locales: true
    locale_prefix: ''
    pretty_name: fennec-${version}.${locale}.${filename_platform}.buildhub.json
    checksums_path: fennec-${version}.${locale}.${filename_platform}.buildhub.json
  target.common.tests.tar.gz:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.common.tests.tar.gz
    checksums_path: fennec-${version}.${locale}.${filename_platform}.common.tests.tar.gz
  target.cppunittest.tests.tar.gz:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.cppunittest.tests.tar.gz
    checksums_path: fennec-${version}.${locale}.${filename_platform}.cppunittest.tests.tar.gz
  target.crashreporter-symbols.zip:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.crashreporter-symbols.zip
    checksums_path: fennec-${version}.${locale}.${filename_platform}.crashreporter-symbols.zip
  target.json:
    <<: *default
    all_locales: true
    pretty_name: fennec-${version}.${locale}.${filename_platform}.json
    checksums_path: fennec-${version}.${locale}.${filename_platform}.json
  target.mochitest.tests.tar.gz:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.mochitest.tests.tar.gz
    checksums_path: fennec-${version}.${locale}.${filename_platform}.mochitest.tests.tar.gz
  target.mozinfo.json:
    <<: *default
    all_locales: true
    pretty_name: fennec-${version}.${locale}.${filename_platform}.mozinfo.json
    checksums_path: fennec-${version}.${locale}.${filename_platform}.mozinfo.json
  target.reftest.tests.tar.gz:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.reftest.tests.tar.gz
    checksums_path: fennec-${version}.${locale}.${filename_platform}.reftest.tests.tar.gz
  target.talos.tests.tar.gz:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.talos.tests.tar.gz
    checksums_path: fennec-${version}.${locale}.${filename_platform}.talos.tests.tar.gz
  target.awsy.tests.tar.gz:
    <<: *default
    pretty_name: fennec-${version}.${locale}.${filename_platform}.awsy.tests.tar.gz
    checksums_path: fennec-${version}.${locale}.${filename_platform}.awsy.tests.tar.gz
  target.test_packages.json:
    <<: *default
    all_locales: true
    pretty_name: fennec-${version}.${locale}.${filename_platform}.test_packages.json
    checksums_path: fennec-${version}.${locale}.${filename_platform}.test_packages.json
  target.txt:
    <<: *default
    all_locales: true
    pretty_name: fennec-${version}.${locale}.${filename_platform}.txt
    checksums_path: fennec-${version}.${locale}.${filename_platform}.txt
  target.web-platform.tests.tar.gz:
    <<: *default
    description: "Web platform test suite <TODO>"
    pretty_name: fennec-${version}.${locale}.${filename_platform}.web-platform.tests.tar.gz
    checksums_path: fennec-${version}.${locale}.${filename_platform}.web-platform.tests.tar.gz
  target.xpcshell.tests.tar.gz:
    <<: *default
    description: "XPCShell test suite <TODO>"
    pretty_name: fennec-${version}.${locale}.${filename_platform}.xpcshell.tests.tar.gz
    checksums_path: fennec-${version}.${locale}.${filename_platform}.xpcshell.tests.tar.gz
  target_info.txt:
    <<: *default
    all_locales: true
    description: "File containing the buildID for the particular release"
    pretty_name: fennec-${version}.${locale}.${filename_platform}_info.txt
    checksums_path: fennec-${version}.${locale}.${filename_platform}_info.txt
  mozharness.zip:
    <<: *default
    pretty_name: mozharness.zip
    checksums_path: mozharness.zip
  robocop.apk:
    <<: *default
    all_locales: true
    pretty_name: robocop.apk
    checksums_path: robocop.apk
  target.jsshell.zip:
    <<: *default
    pretty_name: jsshell-${filename_platform}.zip
    checksums_path: jsshell-${filename_platform}.zip
  target.apk:
    <<: *default
    all_locales: true
    from:
      - build-signing
      - nightly-l10n-signing
    pretty_name: fennec-${version}.${locale}.${filename_platform}.apk
    checksums_path: fennec-${version}.${locale}.${filename_platform}.apk
    update_balrog_manifest:
      by-locale:
        multi: true
        default: false
