---
metadata:
  name: "Beetmover for checksums artifacts"
  description: "Uploads checksum files to s3 buckets"
  owner: "release@mozilla.com"
s3_bucket_paths:
  by-platform:
    .*devedition.*:
      - pub/devedition/nightly
    default:
      - pub/firefox/nightly
default_locales:  # if given an empty locale, use these locales
  - en-US
tasktype_map:  # Map task reference to task type.
  checksums-signing: signing
platform_names:
  path_platform: ''
  filename_platform:
    by-platform:
      linux-.*: 'linux-i686'
      linux64.*: 'linux-x86_64'
      macosx64.*: 'mac'
      win32.*: 'win32'
      win64.*: 'win64'

# A default entry, which the mappings below extend and override.
# Final 'destinations' will be the product of:
# s3_bucket_paths + destinations + locale_prefix + pretty_name
default: &default
  from:
    - checksums-signing
  all_locales: true
  description: "TODO"
  locale_prefix: ''
  source_path_modifier: ''
  destinations:  # locale_prefix is appended
    by-locale:
      en-US:
        - latest-${branch}
        - latest-${branch}-l10n
        - ${year}/${month}/${upload_date}-${branch}-${path_platform}
      default:
        - latest-${branch}-l10n
        - ${year}/${month}/${upload_date}-${branch}-l10n

# Configuration for individual files. Extends 'default', above.
mapping:
  target.checksums:
    <<: *default
    pretty_name: firefox-${version}.${locale}.${filename_platform}.checksums
    checksums_path: firefox-${version}.${locale}.${filename_platform}.checksums
  target.checksums.asc:
    <<: *default
    pretty_name: firefox-${version}.${locale}.${filename_platform}.checksums.asc
    checksums_path: firefox-${version}.${locale}.${filename_platform}.checksums.asc
