---
metadata:
  name: "Beetmover for checksums artifacts"
  description: "Uploads checksum files to s3 buckets"
  owner: "release@mozilla.com"
s3_bucket_paths:
  by-platform:
    fennec-release:
      - pub/mobile/candidates
    devedition-release:
      - pub/devedition/candidates
    firefox-release:
      - pub/firefox/candidates
default_locales:  # if given an empty locale, use these locales
  - en-US
tasktype_map:  # Map task reference to task type.
  release-generate-checksums-signing: signing
  release-generate-checksums: build
platform_names:
  path_platform: ''
  filename_platform: ''

# A default entry, which the mappings below extend and override.
# Final 'destinations' will be the product of:
# s3_bucket_paths + destinations + locale_prefix + pretty_name
default: &default
  from:
    - release-generate-checksums-signing
  all_locales: true
  description: "TODO"
  locale_prefix: ''
  source_path_modifier: ''
  destinations:  # locale_prefix is appended
    - ${version}-candidates/build${build_number}

# Configuration for individual files. Extends 'default', above.
mapping:
  SHA256SUMMARY:
    <<: *default
    from:
      - release-generate-checksums
    pretty_name: SHA256SUMMARY
    checksums_path: SHA256SUMMARY
  SHA512SUMMARY:
    <<: *default
    from:
      - release-generate-checksums
    pretty_name: SHA512SUMMARY
    checksums_path: SHA512SUMMARY
  KEY:
    <<: *default
    pretty_name: KEY
    checksums_path: KEY
  SHA256SUMS:
    <<: *default
    pretty_name: SHA256SUMS
    checksums_path: SHA256SUMS
  SHA256SUMS.asc:
    <<: *default
    pretty_name: SHA256SUMS.asc
    checksums_path: SHA256SUMS.asc
  SHA512SUMS:
    <<: *default
    pretty_name: SHA512SUMS
    checksums_path: SHA512SUMS
  SHA512SUMS.asc:
    <<: *default
    pretty_name: SHA512SUMS.asc
    checksums_path: SHA512SUMS.asc
