/* Generated by wayland-scanner 1.23.90 */

/*
 * SPDX-FileCopyrightText: 2017 David Edmundson
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
#  define __has_attribute(x) 0 /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#  define WL_PRIVATE __attribute__((visibility("hidden")))
#else
#  define WL_PRIVATE
#endif

extern const struct wl_interface org_kde_kwin_appmenu_interface;
#pragma GCC visibility push(default)
extern const struct wl_interface wl_surface_interface;
#pragma GCC visibility pop

static const struct wl_interface* appmenu_types[] = {
    NULL,
    NULL,
    &org_kde_kwin_appmenu_interface,
    &wl_surface_interface,
};

static const struct wl_message org_kde_kwin_appmenu_manager_requests[] = {
    {"create", "no", appmenu_types + 2},
    {"release", "2", appmenu_types + 0},
};

WL_PRIVATE const struct wl_interface org_kde_kwin_appmenu_manager_interface = {
    "org_kde_kwin_appmenu_manager",        2, 2,
    org_kde_kwin_appmenu_manager_requests, 0, NULL,
};

static const struct wl_message org_kde_kwin_appmenu_requests[] = {
    {"set_address", "ss", appmenu_types + 0},
    {"release", "", appmenu_types + 0},
};

WL_PRIVATE const struct wl_interface org_kde_kwin_appmenu_interface = {
    "org_kde_kwin_appmenu", 2, 2, org_kde_kwin_appmenu_requests, 0, NULL,
};
