/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright © 2025 Vlad Zahorodnii
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
#  define __has_attribute(x) 0 /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#  define WL_PRIVATE __attribute__((visibility("hidden")))
#else
#  define WL_PRIVATE
#endif

#pragma GCC visibility push(default)
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface xdg_surface_interface;
#pragma GCC visibility pop
extern const struct wl_interface xx_pip_v1_interface;

static const struct wl_interface* xx_pip_v1_types[] = {
    NULL,
    NULL,
    NULL,
    NULL,
    &xx_pip_v1_interface,
    &xdg_surface_interface,
    &wl_surface_interface,
    &wl_seat_interface,
    NULL,
    &wl_seat_interface,
    NULL,
    NULL,
};

static const struct wl_message xx_pip_shell_v1_requests[] = {
    {"destroy", "", xx_pip_v1_types + 0},
    {"get_pip", "no", xx_pip_v1_types + 4},
};

WL_PRIVATE const struct wl_interface xx_pip_shell_v1_interface = {
    "xx_pip_shell_v1", 1, 2, xx_pip_shell_v1_requests, 0, NULL,
};

static const struct wl_message xx_pip_v1_requests[] = {
    {"destroy", "", xx_pip_v1_types + 0},
    {"set_app_id", "s", xx_pip_v1_types + 0},
    {"set_origin", "o", xx_pip_v1_types + 6},
    {"set_origin_rect", "iiuu", xx_pip_v1_types + 0},
    {"move", "ou", xx_pip_v1_types + 7},
    {"resize", "ouu", xx_pip_v1_types + 9},
};

static const struct wl_message xx_pip_v1_events[] = {
    {"closed", "", xx_pip_v1_types + 0},
    {"configure_bounds", "ii", xx_pip_v1_types + 0},
    {"configure_size", "ii", xx_pip_v1_types + 0},
};

WL_PRIVATE const struct wl_interface xx_pip_v1_interface = {
    "xx_pip_v1", 1, 6, xx_pip_v1_requests, 3, xx_pip_v1_events,
};
