// generated by diplomat-tool
import type { CalendarKind } from "./CalendarKind"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";


/**
 * See the [Rust documentation for `MismatchedCalendarError`](https://docs.rs/icu/latest/icu/datetime/struct.MismatchedCalendarError.html) for more information.
 */
type DateTimeMismatchedCalendarError_obj = {
    thisKind: CalendarKind;
    dateKind?: CalendarKind | null;
};



export class DateTimeMismatchedCalendarError {
    get thisKind(): CalendarKind;
    set thisKind(value: CalendarKind);
    get dateKind(): CalendarKind | null;
    set dateKind(value: CalendarKind | null);
    /** Create `DateTimeMismatchedCalendarError` from an object that contains all of `DateTimeMismatchedCalendarError`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    static fromFields(structObj : DateTimeMismatchedCalendarError_obj) : DateTimeMismatchedCalendarError;



    constructor(structObj: DateTimeMismatchedCalendarError_obj);
}