// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";


/**
 * An error when formatting a datetime.
 *
 * Currently the only reachable error here is a missing time zone variant. If you encounter
 * that error, you need to call `with_variant` or `infer_variant` on your `TimeZoneInfo`.
 *
 * Additional information: [1](https://docs.rs/icu/latest/icu/datetime/unchecked/enum.FormattedDateTimeUncheckedError.html)
 */


export class DateTimeWriteError {

    static fromValue(value: DateTimeWriteError | string): DateTimeWriteError;

    get value(): string;

    get ffiValue(): number;

    static Unknown : DateTimeWriteError;
    static MissingTimeZoneVariant : DateTimeWriteError;


    constructor(value: DateTimeWriteError | string );
}