// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";


/**
 * Increment used in a rounding operation.
 *
 * See the [Rust documentation for `RoundingIncrement`](https://docs.rs/fixed_decimal/latest/fixed_decimal/enum.RoundingIncrement.html) for more information.
 */


export class DecimalRoundingIncrement {

    static fromValue(value: DecimalRoundingIncrement | string): DecimalRoundingIncrement;

    get value(): string;

    get ffiValue(): number;

    static MultiplesOf1 : DecimalRoundingIncrement;
    static MultiplesOf2 : DecimalRoundingIncrement;
    static MultiplesOf5 : DecimalRoundingIncrement;
    static MultiplesOf25 : DecimalRoundingIncrement;


    constructor(value: DecimalRoundingIncrement | string );
}