// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";


/**
 * Additional information: [1](https://docs.rs/fixed_decimal/latest/fixed_decimal/struct.LimitError.html)
 */


export class DecimalLimitError {
    /** Create `DecimalLimitError` from an object that contains all of `DecimalLimitError`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    static fromFields(structObj) {
        return new DecimalLimitError(structObj);
    }

    #internalConstructor(structObj) {
        if (typeof structObj !== "object") {
            throw new Error("DecimalLimitError's constructor takes an object of DecimalLimitError's fields.");
        }

        return this;
    }



    constructor(structObj) {
        return this.#internalConstructor(...arguments)
    }
}