// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";


/**
 * The sign of a Decimal, as shown in formatting.
 *
 * See the [Rust documentation for `Sign`](https://docs.rs/fixed_decimal/latest/fixed_decimal/enum.Sign.html) for more information.
 */


export class DecimalSign {

    static fromValue(value: DecimalSign | string): DecimalSign;

    get value(): string;

    get ffiValue(): number;

    static None : DecimalSign;
    static Negative : DecimalSign;
    static Positive : DecimalSign;


    constructor(value: DecimalSign | string );
}