// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class TimeZoneVariant {

    static fromValue(value: TimeZoneVariant | string): TimeZoneVariant;

    get value(): string;

    get ffiValue(): number;

    static Standard : TimeZoneVariant;
    static Daylight : TimeZoneVariant;


    /**
     * Sets the `variant` field to "daylight" time.
     *
     * See the [Rust documentation for `from_rearguard_isdst`](https://docs.rs/icu/latest/icu/time/zone/enum.TimeZoneVariant.html#method.from_rearguard_isdst) for more information.
     *
     * See the [Rust documentation for `with_variant`](https://docs.rs/icu/latest/icu/time/struct.TimeZoneInfo.html#method.with_variant) for more information.
     *
     * Additional information: [1](https://docs.rs/icu/latest/icu/time/zone/enum.TimeZoneVariant.html)
     */
    fromRearguardIsdst(isdst: boolean): TimeZoneVariant;

    constructor(value: TimeZoneVariant | string );
}