/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIInputStream.idl"

interface nsIURI;

/**
 * nsIAndroidContentInputStream
 *
 * Provides scriptable methods for initializing a nsIInputStream
 * implementation with an content:// URI of Android.
 */
[scriptable, builtinclass, uuid(6187e14f-a137-486c-9c31-8eefe645f26b)]
interface nsIAndroidContentInputStream : nsIInputStream {
    void init(in nsIURI uri);
};
