# Standard 'directives.txt' prologues for jit-tests
harness_directive = "|jit-test| skip-if: true"
directive = "|jit-test| test-also=--wasm-compiler=optimizing; test-also=--wasm-compiler=baseline; test-also=--setpref=wasm_test_serialization=true; test-also=--test-wasm-await-tier2; test-also=--disable-wasm-huge-memory; skip-variant-if: --disable-wasm-huge-memory, !wasmHugeMemorySupported(); local-include:harness/harness.js"

# Failing tests across all testsuites
excluded_tests = [
  # fiddly text-format rules we don't care about
  "^annotations.wast",
  "^id.wast",
]

[[repos]]
name = "spec"
url = "https://github.com/WebAssembly/spec"
branch = "wasm-3.0"
excluded_tests = []
directive = "; test-also=--no-avx; skip-variant-if: --no-avx, !getBuildConfiguration('x86') && !getBuildConfiguration('x64') || getBuildConfiguration('simulator')"

# Example proposal config:
#
# [[repos]]
# name = "exception-handling"
# url = "https://github.com/WebAssembly/exception-handling"
# branch = "main"
# parent = "spec"
# excluded_tests = [
#   "^data.wast.js",
#   "^elem.wast.js",
# ]
