[package]
name = "profiler_helper"
version = "0.1.0"
authors = ["Markus Stange <mstange@themasta.com>"]

[dependencies]
memmap = "0.6.2"

[dependencies.object]
version = "0.10.0"
optional = true
default-features = false
features = ["std"]

[dependencies.thin-vec]
version = "0.1.0"
features = ["gecko-ffi"]

[features]
parse_elf = ["object"]
