[package]
name = "jsrust_shared"
version = "0.1.0"
authors = ["The Spidermonkey developers"]

[lib]
crate-type = ["rlib"]
name = "jsrust_shared"
path = "lib.rs"

[dependencies]
baldrdash = { path = "../../wasm/cranelift" }

[build-dependencies]
bindgen = {version = "0.43", default-features = false} # disable `logging` to reduce code size

# Uncomment this to enable perf support in release mode.
#[profile.release]
#debug = true
