/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, builtinclass, uuid(79c99e25-8b06-4e68-8935-bdbe22fa4010)]
interface nsICookieValidation : nsISupports
{
  cenum ValidationError : 32 {
    eOK,
    eRejectedEmptyNameAndValue,
    eRejectedNameValueOversize,
    eRejectedInvalidCharName,
    eRejectedInvalidCharValue,
    eRejectedInvalidPath,
    eRejectedInvalidDomain,
    eRejectedInvalidPrefix,
    eRejectedNoneRequiresSecure,
    eRejectedPartitionedRequiresSecure,
    eRejectedHttpOnlyButFromScript,
    eRejectedSecureButNonHttps,
    eRejectedForNonSameSiteness,
    eRejectedAttributePathOversize,
    eRejectedAttributeDomainOversize,
  };

  readonly attribute nsICookieValidation_ValidationError result;

  // This returns an empty string if the result is `eOK`.
  readonly attribute AString errorString;
};
